set_requester(function (request) {
  request <- gsub_request(request, "https\\://api.openai.com/v1/", "a/")
  request <- gsub_request(request, "/threads", "/t")
  request <- gsub_request(request, "/chat", "/c")
  request <- gsub_request(request, "/files", "/f")
  request <- gsub_request(request, "/messages", "/m")
  request <- gsub_request(request, "/assistants", "/a")
  request <- gsub_request(request, "/runs", "/r")
  request <- gsub_request(request, "/steps", "/s")
  request <- gsub_request(request, "thread_", "t_")
  request <- gsub_request(request, "msg_", "m_")
  request <- gsub_request(request, "run_", "r_")
  request <- gsub_request(request, "step_", "s_")
  request <- gsub_request(request, "file-sN6eG4TkNq2Quj1LpgCdUVdo", "file-s")
  request <- gsub_request(request, "file-P6XH5bDZSo311u3yKlM6bFFn", "file-P")
  request <- gsub_request(request, "s_.+\\/", "longstep/")
  request <- gsub_request(request, "s_.+", "longstep")
  request
})
